language: php

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer install --no-interaction

script:
  - composer test-cl